pySEZ/product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.ProductListView.as_view(), name="product-list"),
    path("create/", views.ProductCreateView.as_view(), name="product-create"),
    path("<int:pk>/", views.ProductDetailView.as_view(), name="product-detail"),
    path("<int:pk>/update/", views.ProductUpdateView.as_view(), name="product-update"),
    path("<int:pk>/delete/", views.ProductDeleteView.as_view(), name="product-delete"),
]

pySEZ/pySEZ/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("clients/", include("client.urls")),
    path("products/", include("product.urls")),
    path("orders/", include("order.urls")),
    path("accounts/", include("user.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

pySEZ/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="user-login"),
    path("logout/", views.LogoutView.as_view(), name="user-logout"),
]

pySEZ/order/models.py
from client.models import Client
from django.contrib import admin
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Prefetch
from marker.models import Marker
from product.models import Product
from status.models import Status

from pySEZ.utils import get_sentinel_client, get_sentinel_user


class Order(models.Model):
    class Meta:
        ordering = ["-status__state", "-deadline", "-date_created"]

    client = models.ForeignKey(Client, related_name="orders", on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_finished = models.DateTimeField(blank=True, null=True)
    deadline = models.DateField(blank=True, null=True)
    note = models.TextField(blank=True)
    discount = models.DecimalField(
        validators=[MinValueValidator(-100), MaxValueValidator(999)],
        default=0,
        max_digits=5,
        decimal_places=2,
    )
    user = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user))
    status = models.ForeignKey(
        Status,
        on_delete=models.CASCADE,
    )
    products = models.ManyToManyField(
        Product, related_name="orders", through="OrderItem"
    )
    markers = models.ManyToManyField(Marker, related_name="markers", blank=True)

    # status_log = models.ForeignKey(StatusLog, on_delete=models.CASCADE)

    def __str__(self):
        return (
            f"{self.client} | "
            f'Date: {self.date_created.strftime("%Y-%m-%d") } | '
            f"Status: {self.status} | "
            f'Products: {", ".join([p.name for p in self.products.all()])}'
        )

    @property
    def discounted_price(self) -> float:
        return self.total_price + (self.total_price * self.discount / 100)

    @property
    def total_price(self) -> float:
        # return sum(oi.price for oi in self.orderitem_set.all())
        items = self.orderitem_set.all().prefetch_related(Prefetch("product"))
        return sum(item.product.unit_price * item.quantity for item in items)

    @admin.display
    def get_products(self):
        return ", ".join([p.name for p in self.products.all()])


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.DecimalField(default=1, max_digits=10, decimal_places=2)
    note = models.TextField(blank=True)

    def __str__(self):
        return f"{self.product.name} - ({self.quantity} {self.product.unit.name})"

    # def get_absolute_url(self):
    #     return redirect("order-detail", pk=self.pk)

    @property
    def price(self):
        return self.quantity * self.product.unit_price

pySEZ/product/models.py
from django.db import models


class Unit(models.Model):
    name = models.CharField(max_length=50)
    minvalue = models.DecimalField(
        max_digits=20, decimal_places=2, default=0, blank=True, null=True
    )
    maxvalue = models.DecimalField(
        max_digits=20, decimal_places=2, blank=True, null=True
    )
    step = models.DecimalField(
        max_digits=5, decimal_places=2, default=1, blank=True, null=True
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    unit_price = models.DecimalField(default=0.0, max_digits=20, decimal_places=2)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} ({self.unit_price}/{self.unit.name})"

    @property
    def orders_new(self):
        return self.orders.filter(status__state="NEW")

    @property
    def orders_pending(self):
        return self.orders.filter(status__state="PENDING")

    @property
    def orders_done(self):
        return self.orders.filter(status__state="DONE")

pySEZ/product/forms.py
from django.forms import ModelForm
from django import forms
from .models import Product, Unit


class UnitForm(ModelForm):
    class Meta:
        model = Unit
        fields = ("name", "minvalue", "maxvalue", "step")


class ProductForm(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(ModelForm, self).__init__(*args, **kwargs)
    #     self.model = Product
    #     self.fields['unit_price'].widget.attrs.update(
    #         {'min': self.get_object().unit.minvalue,
    #          'max': self.get_object().unit.maxvalue,
    #          'step': self.get_object().unit.step})

    # def get_object(self):
    #     obj = self.model.objects.get(pk=self.instance.pk)
    #     return obj

    class Meta:
        model = Product
        fields = (
            "name",
            "unit",
            "unit_price",
        )

pySEZ/product/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .forms import ProductForm
from .models import Product


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    ordering = ["name"]
    paginate_by = 10

    def get_queryset(self):
        query = super().get_queryset()
        if s := self.request.GET.get("search"):
            query = query.filter(name__icontains=s)
        return query

    def get_template_names(self):
        return (
            ["product/_product_list.html"]
            if self.request.htmx
            else ["product/product_list.html"]
        )


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        match self.request.GET.get("orders_state"):
            case "NEW":
                context["orders_filtered"] = self.object.orders_new
            case "PENDING":
                context["orders_filtered"] = self.object.orders_pending
            case "DONE":
                context["orders_filtered"] = self.object.orders_done
            case _:
                context["orders_filtered"] = self.object.orders.all()
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        if self.request.htmx:
            return self.request.META.get("HTTP_REFERER")
        else:
            return reverse_lazy("product-detail", kwargs={"pk": self.object.pk})

    def get_template_names(self):
        return ["scraps/_edit_form.html"] if self.request.htmx else ["edit_form.html"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "New product"
        context["action"] = reverse("product-create")
        return context


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        # return self.request.META.get("HTTP_REFERER")
        return reverse_lazy("product-list")

    def get_template_names(self):
        return ["scraps/_edit_form.html"] if self.request.htmx else ["edit_form.html"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Edit product"
        context["action"] = reverse("product-update", args=[self.object.pk])
        return context


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["question"] = "Delete product?"
        context["subject"] = self.object
        context["action"] = reverse("product-delete", args=[self.object.pk])
        return context

    def get_template_names(self):
        return (
            ["scraps/_confirm_delete.html"]
            if self.request.htmx
            else ["confirm_delete.html"]
        )

    def get_success_url(self):
        return self.request.META.get("HTTP_REFERER")
        # return reverse_lazy("product-list")

pySEZ/product/templates/product/_product_form.html
{% comment %} load into modal form {% endcomment %}
<div class="modal-header ">
    <h5 class="modal-title" id="exampleModalLabel">{{ title }}</h5>
    <button type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"></button>
</div>
<form method="POST" id="confirm" role="dialog" action="{{ action }}">
    {% csrf_token %}
    <div class="modal-body">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
        </div>
    </div>
    <div class="modal-footer">
        <button type="button"
        class="btn btn-secondary btn-sm"
        data-bs-dismiss="modal">Anuluj</button>
        <button type="submit" class="btn btn-primary btn-sm text-light">Zapisz</button>
    </div>
</form>

pySEZ/product/templates/product/_product_list.html
<div id="partial">
    <table class="table table-hover table-dynamic">
        <thead class="table-dark">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Unit</th>
                <th scope="col">Unit Price</th>
                <th scope="col" class="text-end">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for product in product_list %}
                <tr>
                    <td data-label="NAME">
                        <a href="{% url 'product-detail' product.pk %}">{{ product.name }}</a>
                    </td>
                    <td data-label="UNIT">{{ product.unit.name }}</td>
                    <td data-label="UNIT PRICE price">{{ product.unit_price }}</td>
                    <td data-label="ACTION" class="text-end">
                        <div class="btn-group">
                            <a class="btn btn-outline-primary btn-sm"
                               title="Edit"
                               href="{% url 'product-update' product.pk %}"
                               data-bs-toggle="modal"
                               data-bs-target="#modal"
                               hx-get="{% url 'product-update' product.pk %}"
                               hx-target=".modal-content"
                               hx-trigger="click"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                            <a class="confirm btn btn-outline-danger btn-sm"
                               title="Delete"
                               data-bs-toggle="modal"
                               data-bs-target="#modal"
                               hx-get="{% url 'product-delete' product.pk %}"
                               hx-target=".modal-content"
                               hx-trigger="click"><i class="fa fa-trash" aria-hidden="true"></i></a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="d-flex flex-row-reverse p-0">{% include 'scraps/pagination.html' %}</div>
</div>

pySEZ/product/templates/product/product_detail.html
{% extends "../index.html" %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            <div class="card bg-secondary mb-3 text-light">
                <div class="card-body p-0">
                    <row class="d-flex flex-row align-items-center justify-content-between">
                    <div class="ps-3">
                        <i class="fa fa-inbox fa-3x"></i>
                    </div>
                    <div class="pe-4">
                        <p class="fs-1 fw-bold m-0 text-end">{{ object.orders.count|default:'--' }}</p>
                    </div>
                    </row>
                </div>
                <a href="#">
                    <div class="card-footer text-light fs-5">Total orders count</div>
                </a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card bg-danger mb-3 text-light">
                <div class="card-body p-0">
                    <row class="d-flex flex-row align-items-center justify-content-between">
                    <div class="ps-3">
                        <i class="fa fa-pencil-square-o fa-3x"></i>
                    </div>
                    <div class="pe-4">
                        <p class="fs-1 fw-bold m-0 text-end">{{ object.orders_new.count|default:"--" }}</p>
                    </div>
                    </row>
                </div>
                <a href="#">
                    <div class="card-footer text-light fs-5">New orders count</div>
                </a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card bg-info mb-3 text-light">
                <div class="card-body p-0">
                    <row class="d-flex flex-row align-items-center justify-content-between">
                    <div class="ps-3">
                        <i class="fa fa-hourglass-half fa-3x"></i>
                    </div>
                    <div class="pe-4">
                        <p class="fs-1 fw-bold m-0 text-end">{{ object.orders_pending.count|default:"--" }}</p>
                    </div>
                    </row>
                </div>
                <a href="#">
                    <div class="card-footer text-light fs-5">Pending orders count</div>
                </a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card bg-success mb-3 text-light">
                <div class="card-body p-0">
                    <row class="d-flex flex-row align-items-center justify-content-between">
                    <div class="ps-3">
                        <i class="fa fa-check-square-o fa-3x"></i>
                    </div>
                    <div class="pe-4">
                        <p class="fs-1 fw-bold m-0 text-end">{{ object.orders_done.count|default:"--" }}</p>
                    </div>
                    </row>
                </div>
                <a href="#">
                    <div class="card-footer text-light fs-5">Finished orders count</div>
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 gy-3">
            <div class="card shadow">
                <div class="card-header bg-primary text-light fw-bold fs-5">Actions</div>
                <div class="d-grid p-3">
                    <a href="3"
                       class="btn btn-outline-primary m-3 p-5"
                       data-bs-toggle="modal"
                       data-bs-target="#modal"
                       hx-get="#"
                       hx-target=".modal-content"
                       hx-trigger="click"><i class="fa fa-pencil" aria-hidden="true"> Edit</i></a>
                    <a class="confirm btn btn-outline-danger m-3 p-5"
                       data-bs-toggle="modal"
                       data-bs-target="#modal"
                       hx-get="#"
                       hx-target=".modal-content"
                       hx-trigger="click"><i class="fa fa-trash" aria-hidden="true"> Delete</i></a>
                </div>
            </div>
        </div>
        <div class="col-md-6 gy-3">INCLUDE</div>
    </div>
    <div class="row mt-3">
        <div class="col-md-12 mt-3">
            <div class="card shadow">
                <div class="card-header bg-primary text-light fw-bold">
                    <div class="d-flex align-items-center">
                        <div class="p-2 flex-grow-1 fs-5">Order List</div>
                        <div class="p-2">
                            <span class="htmx-indicator me-2">
                                <img width="30px" src="{% static "assets/images/three-dots.svg" %}"/>
                            </span>
                        </div>
                    </div>
                </div>
                <div id="partial">
                    {% with order_list=orders_filtered %}
                        {% include '../order/_order_list.html' %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

pySEZ/product/templates/product/product_list.html
{% extends "../index.html" %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow">
                <div class="card-header bg-primary text-light fw-bold">
                    <div class="d-flex align-items-center">
                        <div class="p-2 flex-grow-1 fs-5">Product List</div>
                        <div class="p-2">
                            <span class="htmx-indicator me-2">
                                <img width="30px" src="{% static "assets/images/three-dots.svg" %}"/>
                            </span>
                        </div>
                        <div class="p-2">
                            <div>
                                <input class="form-control form-control-sm"
                                       type="search"
                                       name="search"
                                       placeholder="Search"
                                       value="{{ request.GET.search }}"
                                       hx-swap="outerHTML"
                                       hx-get="{% url 'product-list' %}"
                                       hx-preserve="false"
                                       hx-refresh="true"
                                       hx-trigger="keyup changed delay:500ms, search"
                                       hx-target="#partial"
                                       hx-indicator=".htmx-indicator"/>
                            </div>
                        </div>
                        <div class="p-2">
                            <a class="btn btn-sm btn-light text-dark form-button"
                               href="{% url 'product-create' %}"
                               data-bs-toggle="modal"
                               data-bs-target="#modal"
                               hx-refresh="true"
                               hx-get="{% url 'product-create' %}"
                               hx-target=".modal-content"
                               hx-trigger="click"><i class="fa fa-user-plus" aria-hidden="true"></i> New product</a>
                        </div>
                    </div>
                </div>
                <div id="partial">{% include "./_product_list.html" %}</div>
            </div>
        </div>
    </div>
{% endblock content %}